#!/usr/bin/env python3
import sys
from jack.__main__ import main, build_parser
import os
import fcntl
import struct
import time
import argparse


os.environ["JACK_STATE_DIR"] = "/var/lib/jack"

# Constants from linux/cdrom.h
CDROM_DRIVE_STATUS = 0x5326
CDS_TRAY_OPEN      = 2
CDS_NO_DISC        = 1
CDS_DISC_OK        = 4
CDS_DRIVE_NOT_READY = 3

parser = build_parser()
args = parser.parse_args()

fd = os.open(args.device, os.O_RDONLY | os.O_NONBLOCK)
# Get drive status via ioctl
status = fcntl.ioctl(fd, CDROM_DRIVE_STATUS)

if status == CDS_TRAY_OPEN:
    os.close(fd)
    sys.exit(0)
elif status == CDS_NO_DISC:
    os.close(fd)
    sys.exit(0)
elif status == CDS_DRIVE_NOT_READY:
    retries = 0
    while fcntl.ioctl(fd, CDROM_DRIVE_STATUS) != CDS_DISC_OK:
        time.sleep(10)
        retries += 1
        if retries > 6:
            break # still try to queue disc

os.close(fd)

if __name__ == "__main__":
    raise SystemExit(main())
